### ISSUE TITLE
Suggestion on Hyper-parameter Tuning given low eps (eps <= 1)

### ISSUE THREAD

**Issue by boxin-wbx** [DingfanChen/GS-WGAN#2]
Hi,

Thanks a lot for open-sourcing the code.

I am wondering if you have any advice on how to select the proper hyper-parameter given low eps, especially when eps <= 1. 

Thanks :)

**Comment by DingfanChen** [comment]
Hi,
Thanks for your interest.
Eps<=1 is hard to achieve if using the method in its original form. Suggestion/discussion about possible modification of the method/implementation is highly appreciated. Please feel free to contact me.
