### ISSUE TITLE
Have you tested the case of using multiple GPUs?

### ISSUE THREAD

**Issue by 815961618** [DingfanChen/GS-WGAN#3]
Hi, I have tried to train the generator using 4 GPUs. I used your pretrained D and using the **defualt configuration only with different number of GPUs**. The finally generated images are terrible. So, have you tested the case of using multiple GPUs? Should I change some configurations, e.g., noise scale and iterations?

**Comment by tazwar22** [comment]
I've been getting some similar behavior on my own experiments as well. Have you had any luck yet?

**Comment by DingfanChen** [comment]
Hi, we've tested the multiple GPUs case on *Quadro RTX8000* (2 GPUs, default configuration), and obtained results comparable to a single GPU case. We are aware that the results can be affected by the type of GPU hardware and the usage of GPUs. We fell sorry that we are not sure of the exact reason & solution for this issue at the moment.
