### ISSUE TITLE
Poor Generator Performance

### ISSUE THREAD

**Issue by tazwar22** [DingfanChen/GS-WGAN#4]
Hi. I've tried pre-training **1000** Discriminators for 2K iters each (as per the subsampling rate mentioned in the appendix). The metrics (`G_cost`, `D_cost`,`Wasserstein`) are in the [-0.5, 2.4 ish] interval, however the corresponding stats for the Generator that loads and uses these, are much higher (~13 or 11 for each). The metrics don't improve at all (when training for 20K iters in `main.py`) and the final images are all just blank. 
I am using the default noise-multiplier, and default architectures. Am I missing something here?

**Comment by DingfanChen** [comment]
Hi, are you training with a single GPU or multiple GPUs? And could you please let us know your GPU type?

**Comment by tazwar22** [comment]
I initially tried training with 2 GPUs, but eventually tried sticking with just 1 as well. 
GPU TYPE - `NVIDIA GeForce GTX 1080 Ti`
Didn't notice any particular improvement in any case, although I saw slightly lower costs with a DCGAN generator architecture instead of ResNet (images still looked fuzzy and meaningless).

**Comment by BobFengxy** [comment]
the same situation

**Comment by DingfanChen** [comment]
Hi, we are aware that the results can be affected by the type of GPU hardware and the usage of GPUs (We conducted the experiments on Quadro RTX8000). We feel sorry that we are not sure of the exact reason & solution for this issue at the moment. We would help to provide the checkpoints using our hardware, in case you need to compare with our results.

**Comment by BobFengxy** [comment]
Hello, have you tried to generate other image data sets, such as cifar-10, which is three-channel?

**Comment by BobFengxy** [comment]
Hello, why do you set 1000 discriminators? Can only one discriminator be used? I am a novice.

**Comment by DingfanChen** [comment]
> Hello, have you tried to generate other image data sets, such as cifar-10, which is three-channel?

No. The GAN architecture and the hyper-parameters should be adjusted for other image datasets. We would be happy to incorporate new results if you have managed to apply our model to other image datasets.

**Comment by DingfanChen** [comment]
> Hello, why do you set 1000 discriminators? Can only one discriminator be used? I am a novice.

This is used for obtaining a decent level of privacy cost. Please find more details in our paper.
